[2024-05-22T15:48:25.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T15:48:25.392+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_scraping_to_json_dag.save_to_json manual__2024-05-22T15:48:20.899397+00:00 [queued]>
[2024-05-22T15:48:25.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_scraping_to_json_dag.save_to_json manual__2024-05-22T15:48:20.899397+00:00 [queued]>
[2024-05-22T15:48:25.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-22T15:48:25.419+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_to_json> on 2024-05-22 15:48:20.899397+00:00
[2024-05-22T15:48:25.426+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=453) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T15:48:25.428+0000] {standard_task_runner.py:63} INFO - Started process 455 to run task
[2024-05-22T15:48:25.428+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_scraping_to_json_dag', 'save_to_json', 'manual__2024-05-22T15:48:20.899397+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/web_scrapper_test_dag.py', '--cfg-path', '/tmp/tmplbdl3iwg']
[2024-05-22T15:48:25.431+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask save_to_json
[2024-05-22T15:48:25.478+0000] {task_command.py:426} INFO - Running <TaskInstance: web_scraping_to_json_dag.save_to_json manual__2024-05-22T15:48:20.899397+00:00 [running]> on host a140284f2937
[2024-05-22T15:48:25.561+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_scraping_to_json_dag' AIRFLOW_CTX_TASK_ID='save_to_json' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T15:48:20.899397+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T15:48:20.899397+00:00'
[2024-05-22T15:48:25.564+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T15:48:25.575+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T15:48:25.576+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/web_scrapper_test_dag.py", line 28, in save_to_json
    with open('/path/to/your/directory/data.json', 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/directory/data.json'
[2024-05-22T15:48:25.589+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=web_scraping_to_json_dag, task_id=save_to_json, run_id=manual__2024-05-22T15:48:20.899397+00:00, execution_date=20240522T154820, start_date=20240522T154825, end_date=20240522T154825
[2024-05-22T15:48:25.602+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task save_to_json ([Errno 2] No such file or directory: '/path/to/your/directory/data.json'; 455)
[2024-05-22T15:48:25.643+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-22T15:48:25.659+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T15:48:25.662+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
